### PR TITLE
Readme: update python version badge

### PR DESCRIPTION
**Pull request by jstriebel**
Updates the Python version badge.

### CODE REVIEW

**Comment by hotzenklotz** [comment]
This is odd, how Shield.io parses the version. From the code, I can see that they check the PyPi listing for the attribute `Classifiers :: Programming Language`, which currently is:

image

Hence, the `Py3.8` badge is correct. I wonder if we could correct the metadata on PyPi instead and hence fix the bade in the process. (e.g. see Rasa [repo badge](https://github.com/rasaHQ/rasa) and [PyPi](https://pypi.org/project/rasa/)

**Comment by hotzenklotz** [comment]
The "Classifier" info is likely directly filled out by either `poetry publish` or inferred by `PyPi`. In any case it seems to have changed with my last PR on limiting the Python version in our `project.toml`.

webKnossos:
```
[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
```

Rasa:
```
[tool.poetry.dependencies]
python = ">=3.7,<3.10"
```

Note the lack of a space between a space and the lack of any patch version in their string. Perhaps, we try that.

**Comment by jstriebel** [comment]
@hotzenklotz Yes, the reason 3.7 is missing is because of the `>=3.7.1` specification we have. However, this is needed, since some dependencies exclude `3.7.0` specifically, since it contained important bugs. That's why I wanted to adapt the badge manually. However, I just found out that we can manually add classifiers, I'll try that instead:
https://python-poetry.org/docs/pyproject/#classifiers

**Comment by jstriebel** [comment]
Superseded by #722

**Pull request closed without merging**
