### PR TITLE
Bump wkw version

### PR DESCRIPTION
**Pull request by leowe**
- bump to current version (`1.1.16`)

### CODE REVIEW

**Comment by jstriebel** [comment]
All files for the `1.1.15` release have win or mac in their name, probably linux builds are missing?
https://pypi.org/project/wkw/1.1.15/#files

**Comment by leowe** [comment]
> All files for the `1.1.15` release have win or mac in their name, probably linux builds are missing?
> https://pypi.org/project/wkw/1.1.15/#files

Looks like it. @normanrz Do you what's going on there?

**Comment by normanrz** [comment]
The job somehow crashed 🤷  https://github.com/scalableminds/webknossos-wrap/runs/4587889641?check_suite_focus=true

**Comment by normanrz** [comment]
1.1.16 is now released, also for Linux

**Comment by jstriebel** [comment]
@leowe Ping for reminder :-)

**Comment by leowe** [comment]
@jstriebel You can have a look now :)

**Comment by jstriebel** [comment]
@leowe ping

**Comment by jstriebel** [comment]
(@leowe Please let me know if I should take this over in case the poetry setup is too much hustle)

**Comment by jstriebel** [comment]
superseded by #769

**Pull request closed without merging**
